on:
  push:
    branches: [ "main", "github-actions" ]
  pull_request:
    branches: [ "main" ]


jobs:
  inspection:
    runs-on: windows-2019 # or macos-latest, windows-latest
    name: Inspection
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2
        
      - name: Restore Packages
        run: nuget restore Core/WumpusCore.sln
        
      - name: Inspect testing
        uses: muno92/resharper_inspectcode@v1
        with:
          solutionPath: "Core/WumpusTesting/WumpusTesting.csproj"
          dotnetVersion: ${{ steps.setup-dotnet.outputs.dotnet-version }}
          
      - name: Inspect core
        uses: muno92/resharper_inspectcode@v1
        with:
          solutionPath: "Core/WumpusCore/WumpusCore.csproj"
          dotnetVersion: ${{ steps.setup-dotnet.outputs.dotnet-version }}
