on:
  push:
    branches: [ "main", "github-actions" ]
  pull_request:
    branches: [ "main" ]


jobs:
  inspection:
    runs-on: windows-2019 # or macos-latest, windows-latest
    name: Inspection
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        id: setup-dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # [3.1.x, 5.0.x, 6.0.x, 7.0.x, 8.0.x]
      - name: Restore
        run: dotnet restore
      - name: Inspect code
        uses: muno92/resharper_inspectcode@v1
        with:
          solutionPath: ./YourSolution.sln
          dotnetVersion: ${{ steps.setup-dotnet.outputs.dotnet-version }}
