on:
  push:
    branches: [ "main", "github-actions" ]
  pull_request:
    branches: [ "main" ]


jobs:
  inspection:
    runs-on: ubuntu-latest # or macos-latest, windows-latest
    name: Inspection
    steps:
      - name: Checkout
        uses: actions/checkout@v4
          
      - name: Inspect Core
        uses: glassechidna/resharper-action@master
        with:
          solution: Core/WumpusCore.sln
